### ISSUE TITLE
Observation: Styling decisions for plots can make your results look different

### ISSUE THREAD

**Issue by Caealana** [ivan0h/intro-data-capstone-musclehub#4]
https://github.com/ivan0h/intro-data-capstone-musclehub/blob/4dd74c1cadef054b20e856c7f019125d4072bcc2/MuscleHub%20-%20Ivan%20Oregel/musclehub_ivan_oregel.py#L396-L404

This isn't an issue but more of an interesting tidbit to keep in mind when designing data visualizations.
You can manipulate data visualizations to give different impressions.
For example, both plots are created using the same data. Manipulating the range of the y-axis in the following two plots makes the differences between the two groups appear more pronounced in the second plot:
<img width="691" alt="screenshot at feb 23 13-51-55" src="https://user-images.githubusercontent.com/14001120/36608615-ba600d94-18a0-11e8-81e6-184fd76a2b2d.png">

**Comment by ivan0h** [comment]
That's a really good tip. That's one of the reasons why I want to learn python is to better manipulate charts to make them more presentable and understandable to execs. Those are just some of the many things I don't think/know about but will learn as I go. Thank you!
